#!/usr/bin/env python3
"""Make the TikiTakaFootyTV skills + commands portable across coding harnesses.

`.claude/` is the SINGLE SOURCE OF TRUTH. This script regenerates the
harness-specific copies that don't read `.claude/` natively, so the owner edits
one set of files and re-runs `sync` to keep every harness current.

What needs translating per harness:

  SKILLS  (`.claude/skills/<name>/SKILL.md`)
    - Claude Code:  reads `.claude/skills/` natively.
    - OpenCode:     reads `.claude/skills/` AND `.agents/skills/` natively
                    (same `name` + `description` SKILL.md format).
    => Skills are already portable; NOTHING to generate. We only verify them.

  COMMANDS  (`.claude/commands/<name>.md`)
    - Claude Code:  reads `.claude/commands/`.
    - OpenCode:     reads `.opencode/command/` (singular), different frontmatter:
                      * no `allowed-tools`   (tool perms are agent-level there)
                      * no `argument-hint`
                      * `model` must be `provider/model` (e.g. anthropic/claude-haiku-4-5)
                      * body keeps `$ARGUMENTS`, `$1`, !`shell`, @file — compatible
                      * skill references are prose ("invoke the `videospec` skill") — portable
    => We translate each command's frontmatter and copy the body verbatim.

  INSTRUCTIONS
    - OpenCode reads `AGENTS.md`, not `CLAUDE.md`. We bridge with a symlink (or a
      stub that points at CLAUDE.md) so the project context loads there too.

Usage:
    python3 pipeline/sync_harness.py sync     # regenerate all harness copies
    python3 pipeline/sync_harness.py check    # report drift, write nothing (exit 1 if stale)

Pure stdlib — no `uv`, no deps.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CLAUDE_COMMANDS = REPO / ".claude" / "commands"
CLAUDE_SKILLS = REPO / ".claude" / "skills"

GENERATED_BANNER = (
    "<!-- AUTO-GENERATED from {src} by pipeline/sync_harness.py — "
    "edit the SOURCE under .claude/, then re-run `python3 pipeline/sync_harness.py sync`. "
    "Do not edit this file by hand. -->\n"
)

# Bare Claude model id -> the provider-qualified id OpenCode expects.
# The owner can repoint the provider prefix if they run OpenCode against another backend.
MODEL_MAP = {
    "claude-haiku-4-5": "anthropic/claude-haiku-4-5",
    "claude-sonnet-4-6": "anthropic/claude-sonnet-4-6",
    "claude-opus-4-8": "anthropic/claude-opus-4-8",
    "claude-fable-5": "anthropic/claude-fable-5",
}


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Parse a simple `key: value` YAML frontmatter block. Returns (fields, body)."""
    if not text.startswith("---"):
        return {}, text
    lines = text.splitlines(keepends=True)
    # find the closing '---'
    end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return {}, text
    fields: dict[str, str] = {}
    for raw in lines[1:end]:
        if ":" not in raw:
            continue
        key, _, val = raw.partition(":")
        fields[key.strip()] = val.strip()
    body = "".join(lines[end + 1 :])
    return fields, body


def dump_frontmatter(fields: dict[str, str]) -> str:
    out = ["---\n"]
    for k, v in fields.items():
        out.append(f"{k}: {v}\n")
    out.append("---\n")
    return "".join(out)


# ---- OpenCode command translation ------------------------------------------

def to_opencode_command(src_path: Path) -> str:
    """Translate a Claude command file into an OpenCode command file (string)."""
    fields, body = split_frontmatter(src_path.read_text())
    oc: dict[str, str] = {}
    if "description" in fields:
        oc["description"] = fields["description"]
    if "model" in fields:
        m = fields["model"]
        oc["model"] = MODEL_MAP.get(m, m if "/" in m else f"anthropic/{m}")
    # Dropped on purpose: allowed-tools (agent-level in OpenCode), argument-hint (no such field).
    rel = src_path.relative_to(REPO)
    banner = GENERATED_BANNER.format(src=rel)
    return dump_frontmatter(oc) + banner + body.lstrip("\n")


def sync_opencode_commands(write: bool) -> list[str]:
    """Generate .opencode/command/*.md from .claude/commands/*.md. Returns list of stale/changed."""
    dest_dir = REPO / ".opencode" / "command"
    changed: list[str] = []
    srcs = sorted(CLAUDE_COMMANDS.glob("*.md"))
    if write:
        dest_dir.mkdir(parents=True, exist_ok=True)
    for src in srcs:
        new = to_opencode_command(src)
        dest = dest_dir / src.name
        old = dest.read_text() if dest.exists() else None
        if old != new:
            changed.append(str(dest.relative_to(REPO)))
            if write:
                dest.write_text(new)
    return changed


# ---- AGENTS.md bridge ------------------------------------------------------

def sync_agents_md(write: bool) -> list[str]:
    """OpenCode reads AGENTS.md, not CLAUDE.md. Bridge them (symlink, fallback to stub)."""
    agents = REPO / "AGENTS.md"
    changed: list[str] = []
    # If a correct symlink already exists, nothing to do.
    if agents.is_symlink() and os.readlink(agents) == "CLAUDE.md":
        return changed
    if agents.exists() and not agents.is_symlink():
        # A real file exists — don't clobber owner content; leave it.
        return changed
    changed.append("AGENTS.md")
    if write:
        if agents.exists() or agents.is_symlink():
            agents.unlink()
        try:
            agents.symlink_to("CLAUDE.md")
        except OSError:
            # Filesystems without symlink support: write a pointer stub instead.
            agents.write_text(
                "<!-- AUTO-GENERATED by pipeline/sync_harness.py -->\n"
                "# Project instructions\n\n"
                "This project's canonical instructions live in [CLAUDE.md](CLAUDE.md). "
                "Read that file first.\n"
            )
    return changed


# ---- skills verification ---------------------------------------------------

def verify_skills() -> list[str]:
    """Skills are read natively by OpenCode from .claude/skills — just sanity-check them."""
    problems: list[str] = []
    for skill_md in sorted(CLAUDE_SKILLS.glob("*/SKILL.md")):
        fields, _ = split_frontmatter(skill_md.read_text())
        name = fields.get("name", "")
        desc = fields.get("description", "")
        slug = skill_md.parent.name
        if not name:
            problems.append(f"{slug}: missing `name` frontmatter")
        elif name != slug:
            problems.append(f"{slug}: name '{name}' != directory '{slug}' (OpenCode keys on dir+name)")
        if not desc:
            problems.append(f"{slug}: missing `description` frontmatter")
    # the symlinked find-skills lives under .agents/skills — also OpenCode-readable
    return problems


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "sync"
    write = mode == "sync"
    if mode not in ("sync", "check"):
        print(f"usage: {sys.argv[0]} [sync|check]", file=sys.stderr)
        return 2

    cmd_changed = sync_opencode_commands(write)
    agents_changed = sync_agents_md(write)
    skill_problems = verify_skills()

    print("== TikiTakaFootyTV harness sync ==")
    print(f"skills: {len(list(CLAUDE_SKILLS.glob('*/SKILL.md')))} found "
          "(read natively by OpenCode from .claude/skills — no copy needed)")
    if skill_problems:
        print("  ⚠️ skill issues:")
        for p in skill_problems:
            print(f"    - {p}")

    verb = "wrote" if write else "STALE"
    if cmd_changed:
        print(f"opencode commands: {verb} {len(cmd_changed)} →")
        for c in cmd_changed:
            print(f"    - {c}")
    else:
        print("opencode commands: up to date")

    if agents_changed:
        print(f"AGENTS.md: {verb} (bridges OpenCode → CLAUDE.md)")
    else:
        print("AGENTS.md: up to date")

    if mode == "check" and (cmd_changed or agents_changed):
        print("\nOut of date. Run: python3 pipeline/sync_harness.py sync")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
